<template>
  <main class="main">
    <section class="terms-section">
      <br>
      <h1 class="text-white text-center"><b>User Agreement / Terms and Conditions / Cookies Policy.</b></h1>
      <br>
      <div>
        <h2 class="text-center custom-center"><strong>FOR ONLINE REFERENCE ONLY. EACH ACCESS IS BY PERMISSION ONLY.</strong></h2>
        <h2 class="text-center custom-center"><strong>1. USE OF THE WEBSITE</strong></h2>
        <h2 class="text-center">THIS DEMONSTRATIVE TECHNICAL WEBSITE, PROVIDED WITHOUT ANY WARRANTY, IS INTENDED SOLELY FOR IMMEDIATE PERSONAL ONLINE VIEWING, FOR NON-COMMERCIAL AND NONPROFIT PURPOSES. PLEASE READ THIS ENTIRE AGREEMENT BEFORE USING THIS WEBSITE. BY ACCESSING OR USING THIS WEBSITE, INCLUDING ITS DOMAIN NAME(S) OR IP ADDRESSES, CONTENT, OR ANY INTERACTION (SUCH AS CLICKING ON LINKS), YOU ACKNOWLEDGE AND DECLARE THAT YOU ACCEPT THIS USER AGREEMENT. YOUR ACCESS AND USE INDICATE YOUR ACKNOWLEDGMENT, ACCEPTANCE, AND UNCONDITIONAL AGREEMENT TO ALL THE TERMS AND CONDITIONS SET FORTH HEREIN WITHOUT MODIFICATION, AND THIS AGREEMENT TAKES EFFECT IMMEDIATELY. TO REJECT, SIMPLY REFRAIN FROM USING THE WEBSITE AND CLOSE ALL ITS WINDOWS. HOWEVER, YOU MAY NOT ACCESS OR USE THIS WEBSITE IF YOU (OR YOUR GUARDIAN OR LEGAL REPRESENTATIVE) CANNOT ENTER INTO A BINDING CONTRACT OR IN ANY JURISDICTION WHERE THIS USER AGREEMENT IS NOT ENFORCEABLE. YOU AGREE THAT YOUR USE CONSTITUTES ACKNOWLEDGMENT THAT YOU HAVE READ, UNDERSTOOD, AND ACCEPTED ALL TERMS. IF YOU ARE THE OWNER OR OPERATOR OF THE EQUIPMENT USED TO ACCESS THIS WEBSITE, BY ALLOWING SUCH USE, YOU CONSENT AND AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS USER AGREEMENT. IF ACTING ON BEHALF OF ORGANIZATIONS, YOU DECLARE THAT YOU ARE AUTHORIZED TO ACT AS AN AGENT AND ACCEPT THIS USER AGREEMENT ON BEHALF OF YOUR EMPLOYER AND ORGANIZATIONS. YOU AGREE TO USE THE WEBSITE ONLY IN ACCORDANCE WITH THESE USAGE RIGHTS AND ALL APPLICABLE LAWS AND REGULATIONS. YOU MAY NOT: -ATTEMPT TO BYPASS THE WEBSITE'S SECURITY MEASURES. -USE THE WEBSITE IN A WAY THAT MAY HARM IT OR AFFECT ITS PERFORMANCE. -DISASSEMBLE OR DECOMPILE THE WEBSITE.</h2>
        <h2 class="text-center custom-center"><strong>2. CREDITS - THIS PROJECT IS AN IMPLEMENTATION</strong></h2>
        <h2 class="text-center">This project represents an implementation derived from the project initiated by 'TASTEJS': 
        <strong><a href="https://github.com/tastejs/nuxt-movies" target="_blank">'NUXT MOVIES'</a></strong></h2>
        <h2 class="text-center custom-center"><strong>3. DISCLAIMER FOR WEBSITE USE</strong></h2>
        <h2 class="text-center">THE WEBSITE IS PROVIDED "AS IS" AND "AS AVAILABLE." SONARFLIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED, ABOUT THE FUNCTIONALITY, ACCURACY, OR AVAILABILITY OF THE WEBSITE. ADDITIONALLY, IN THE EVENT OF ANY CYBER ATTACK, SECURITY VULNERABILITY, OR UNAUTHORIZED ACCESS TO THE WEBSITE, SONARFLIX WILL NOT BE RESPONSIBLE FOR DAMAGES, LOSSES, OR DISRUPTIONS CAUSED BY IT. USERS ACKNOWLEDGE AND ACCEPT THAT THE SECURITY OF THE WEBSITE MAY BE COMPROMISED, AND THEY USE THE WEBSITE AT THEIR OWN RISK IN SUCH CIRCUMSTANCES. WE TAKE EXTENSIVE AND CONTINUOUS MEASURES TO ENSURE THE SECURITY OF THE WEBSITE, BUT WE DO NOT GUARANTEE ABSOLUTE SECURITY. THE ONLINE SECURITY LANDSCAPE IS CHALLENGING, AND NO SYSTEM CAN CLAIM COMPLETE IMMUNITY AGAINST RISKS. PLEASE BE AWARE THAT OUR PRIMARY GOAL IS TO SAFEGUARD THE INTEGRITY OF THE WEB APPLICATION AND YOUR EXPERIENCE WITH IT. WE ARE COMMITTED TO ENSURING A SECURE ENVIRONMENT FOR YOUR USE. IT IS ESSENTIAL FOR USERS TO TAKE PRECAUTIONS, SUCH AS VERIFYING THE LINKS THEY USE AND USING UPDATED AND SECURE DEVICES AND NETWORKS. IN THE UNLIKELY EVENT OF ANY SECURITY INCIDENT, WE WILL INVESTIGATE IMMEDIATELY, TAKE NECESSARY ACTIONS, AND KEEP YOU INFORMED. THIS DISCLAIMER EXTENDS TO ANY POTENTIAL IMPACT ON USER DATA, SYSTEM INTEGRITY, OR THE OVERALL PERFORMANCE OF THE WEBSITE RESULTING FROM EXTERNAL MALICIOUS ACTIVITIES. USERS ARE ADVISED TO USE THE WEBSITE WITH AWARENESS OF POSSIBLE SECURITY RISKS AND TAKE NECESSARY MEASURES TO PROTECT THEIR DATA AND DEVICES. </h2>
        <h2 class="text-center custom-center"><strong>4. RESPONSIBLE USE OF SONARFLIX AND BEST PRACTICES. IMPORTANT NOTICE:</strong></h2>
        <h2 class="text-center">BY USING SONARFLIX, THE USER ACKNOWLEDGES AND ACCEPTS THAT THE FUNCTIONALITY OF THIS WEBSITE IS DESIGNED EXCLUSIVELY FOR PRESENTATION TO RECRUITERS. THE SONARFLIX PROJECT IS MERELY A DEMONSTRATIVE FEATURE OF TMDB'S API. SONARFLIX, ITS DEVELOPMENT TEAM, AND ANY RELATED ENTITY DO NOT ASSUME ANY RESPONSIBILITY FOR THE MISUSE OF THE API OR ANY OTHER ASPECT OF THE SITE'S FUNCTIONALITY. THE RESPONSIBILITY LIES SOLELY WITH THE USER, WHO MUST USE THE PLATFORM RESPONSIBLY AND ADHERE TO ONLINE BEST PRACTICES WHEN USING THE DATA OBTAINED OF TMDB'S API. IT IS CRUCIAL TO RECOGNIZE THAT ANY MISUSE OF THE FUNCTIONALITY GOES BEYOND OUR PURPOSE. PLEASE CONSIDER THE FOLLOWING BEST PRACTICES: AVOID USING THIS WEB APP FOR ILLEGAL OR MALICIOUS ACTIVITIES. DO NOT USE SONARFLIX IN CRITICAL ENVIRONMENTS OR WITH EXPECTATIONS OF ACTIVE FUNCTIONING. YOUR UNDERSTANDING AND COMPLIANCE WITH THESE GUIDELINES ARE CRUCIAL FOR THE RESPONSIBLE USE OF SONARFLIX. WE APPRECIATE YOUR COOPERATION AND HOPE YOU ENJOY THE DEMONSTRATIVE EXPERIENCE OF OUR SERVICE. FOR MORE INFORMATION SEE THE RESPECTIVE [MIT LICENSE](https://github.com/imprvhub/sonarflix/blob/main/LICENSE) IN THE SONARFLIX REPOSITORY.</h2>
        <h2 class="text-center custom-center"><strong>5. ATTRIBUTIONS:</strong></h2>
        <h2 class="text-center">FOR SOCIAL MEDIA AND SVG ICONS LICENSED UNDER THE CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE - ATTRIBUTION: FONT AWESOME FREE 5.2.0 BY @FONTAWESOME - HTTPS://FONTAWESOME.COM, CC BY 4.0 VIA WIKIMEDIA COMMONS.</h2>
        <h2 class="text-center custom-center"><strong>6. INFORMATION WE COLLECT</strong></h2>
        <h2 class="text-center">SONARFLIX MAY COLLECT AND STORE CERTAIN INFORMATION ABOUT YOUR USE OF THE WEBSITE. THIS INCLUDES NON-PERSONAL INFORMATION SUCH AS DEVICE TYPE, BROWSER TYPE, AND USAGE PATTERNS. OUR PRIVACY POLICY (SEE SECTION 9) PROVIDES FURTHER DETAILS ON HOW WE HANDLE THIS INFORMATION.</h2>
        <h2 class="text-center custom-center"><strong>7. MODIFICATIONS AND TERMINATION</strong></h2>
        <h2 class="text-center">SONARFLIX RESERVES THE RIGHT TO MODIFY, SUSPEND, OR TERMINATE THE WEBSITE AT ANY TIME WITHOUT PRIOR NOTICE.</h2>
        <h2 class="text-center custom-center"><strong>8. LIMITATION OF LIABILITY</strong></h2>
        <h2 class="text-center">SONARFLIX WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM THE USE OR INABILITY TO USE THE WEBSITE.</h2>
        <h2 class="text-center custom-center"><strong>9. PRIVACY POLICY</strong></h2>
        <h2 class="text-center">BY USING OUR WEBSITE, YOU AGREE TO THE USE OF COOKIES. OUR COOKIE POLICY PROVIDES DETAILS ON WHAT COOKIES ARE, HOW WE USE THEM, THE INVOLVEMENT OF THIRD-PARTY PARTNERS, YOUR COOKIE OPTIONS, AND ADDITIONAL INFORMATION. COOKIES ARE SMALL PIECES OF TEXT SENT TO YOUR WEB BROWSER FROM A VISITED WEBSITE. THEY ARE STORED IN YOUR BROWSER, ALLOWING THE WEBSITE OR THIRD PARTIES TO RECOGNIZE YOU, SIMPLIFYING YOUR SUBSEQUENT VISITS AND IMPROVING THE WEBSITE'S UTILITY. DURING YOUR USE OF THE WEBSITE, WE MAY PLACE VARIOUS COOKIE FILES IN YOUR WEB BROWSER, SERVING ESSENTIAL AND ANALYTICAL PURPOSES. IN ADDITION TO OURS, WE MAY USE THIRD-PARTY COOKIES TO REPORT WEBSITE USAGE STATISTICS, DELIVER ADS, ETC. IF YOU WISH TO DELETE OR REJECT COOKIES, PLEASE REFER TO YOUR BROWSER'S HELP PAGES. NOTE THAT SUCH ACTIONS MAY LIMIT FEATURES, PREFERENCE STORAGE, AND PAGE DISPLAY. FOR POPULAR BROWSERS LIKE GOOGLE CHROME, OPERA, MOZILLA FIREFOX, AND SAFARI, YOU CAN FIND SPECIFIC INSTRUCTIONS ON THEIR RESPECTIVE SUPPORT PAGES. EXPLORE ALLABOUTCOOKIES.ORG AND NETWORKADVERTISING.ORG FOR COMPREHENSIVE INSIGHTS.FURTHERMORE, IN THE CONTEXT OF OUR API SERVICE, DATA OBTAINED BELONGS TO PUBLIC TMDB API.</h2>
        <h2 class="text-center custom-center"><strong>10. CONTACT</strong></h2>
        <h2 class="text-center">FOR ANY INQUIRIES OR CONCERNS REGARDING THIS USER AGREEMENT, TERMS AND CONDITIONS, OR PRIVACY POLICIES, PLEASE EMAIL US AT <strong>CONTACT@IVANLUNA.DEV.</strong></h2>
      </div>
      <br>
      <div class="button-container">
        <button class="button button--icon" @click="redirectToHome">
          <!-- eslint-disable-next-line -->
          <span class="txt">Home</span>
        </button>
      </div>
    </section>
  </main>  

</template>
<script>
export default {
  methods: {
    redirectToHome() {
      window.location.href = 'https://sonarflix.netlify.app';
    }
  }
};
</script>
<style scoped>
  h1 {
    text-align: center;
    margin-bottom: 20px; 
    letter-spacing: 2px;
  }

  .button-container {
    display: flex;
    justify-content: center;
    
  }

  .terms-section {
    padding: 10px;
  }

  .button {
    border-radius: 15px;
  }

  h2 {
    text-align: justify;
    letter-spacing: 2px;
    font-size: 11px;
    text-transform: uppercase;
    margin: 0 auto; 
    max-width: 800px; 
    margin-bottom: 20px; 
  }

  .custom-center {
    text-align: center;
  }
</style>
